# Generated by Django 4.1.1 on 2022-12-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['number']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
