# Generated by Django 4.1.1 on 2022-12-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0004_student_files_alter_student_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('number',), 'verbose_name': 'Öğrenci', 'verbose_name_plural': 'Öğrenciler'},
        ),
    ]
